### ISSUE TITLE
can not create CA replica

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#47]
I'm kinda stuck because I realized my replicas are not CA enabled, and I needed one of them to replace my current master.
So I tried to setup a new CA replicate, adding the --setup-ca option to ipa-replica-install-options, 
my ipa-replica-install-options:
```
--password=xxx
--admin-password=xxx
--no-host-dns
--setup-ca
``` 

but the install fails:
Configuring certificate server (pki-tomcatd): Estimated time 3 minutes 30 seconds
```
  [1/22]: creating certificate server user
  [2/22]: configuring certificate server instance
ipa         : CRITICAL failed to configure ca instance Command ''/usr/sbin/pkispawn' '-s' 'CA' '-f' '/tmp/tmpKIDYI0'' returned non-zero exit status 1
  [error] RuntimeError: Configuration of CA failed
Configuration of CA failed
```

in ipareplica-install.log:
```
2015-12-18T18:08:29Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2015-12-18T18:08:29Z DEBUG Starting external process
2015-12-18T18:08:29Z DEBUG args='/usr/sbin/pkispawn' '-s' 'CA' '-f' '/tmp/tmpKIDYI0'
2015-12-18T18:08:50Z DEBUG Process finished, return code=1
2015-12-18T18:08:50Z DEBUG stdout=Loading deployment configuration from /tmp/tmpKIDYI0.
Installing CA into /var/lib/pki/pki-tomcat.
Storing deployment configuration into /etc/sysconfig/pki/tomcat/pki-tomcat/ca/deployment.cfg.
    'pki-tomcat' must still be CONFIGURED!
    (see /var/log/pki-tomcat-install.log)

Installation failed.


2015-12-18T18:08:50Z DEBUG stderr=/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

2015-12-18T18:08:50Z CRITICAL failed to configure ca instance Command ''/usr/sbin/pkispawn' '-s' 'CA' '-f' '/tmp/tmpKIDYI0'' returned non-zero exit status 1
2015-12-18T18:08:50Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 388, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 378, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/cainstance.py", line 673, in __spawn_instance
    raise RuntimeError('Configuration of CA failed')
RuntimeError: Configuration of CA failed

2015-12-18T18:08:50Z DEBUG   [error] RuntimeError: Configuration of CA failed
2015-12-18T18:08:50Z DEBUG   File "/usr/lib/python2.7/site-packages/ipaserver/install/installutils.py", line 642, in run_script
    return_value = main_function()

  File "/usr/sbin/ipa-replica-install", line 704, in main
    CA = cainstance.install_replica_ca(config)

  File "/usr/lib/python2.7/site-packages/ipaserver/install/cainstance.py", line 1869, in install_replica_ca
    subject_base=config.subject_base)

  File "/usr/lib/python2.7/site-packages/ipaserver/install/cainstance.py", line 520, in configure_instance
    self.start_creation(runtime=210)

  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 388, in start_creation
    run_step(full_msg, method)

  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 378, in run_step
    method()

  File "/usr/lib/python2.7/site-packages/ipaserver/install/cainstance.py", line 673, in __spawn_instance
 ```

**Comment by kforner** [comment]
It works now using the latest-systemd branch. Thanks.
