### ISSUE TITLE
Error running freeipa-server

### ISSUE THREAD

**Issue by dmitryint** [adelton/docker-freeipa#55]
The same error as [Error running systemd freeipa-server #46](https://github.com/adelton/docker-freeipa/issues/46)
but on `adelton/freeipa-server:latest`

```
Configuring the web interface (httpd). Estimated time: 1 minute
  [1/19]: setting mod_nss port to 443
  [2/19]: setting mod_nss protocol list to TLSv1.0 - TLSv1.2
  [3/19]: setting mod_nss password file
  [4/19]: enabling mod_nss renegotiate
  [5/19]: adding URL rewriting rules
  [6/19]: configuring httpd
  [7/19]: configure certmonger for renewals
  [8/19]: setting up ssl
  [9/19]: importing CA certificates from LDAP
  [10/19]: setting up browser autoconfig
  [11/19]: publish CA cert
  [12/19]: creating a keytab for httpd
  [13/19]: clean up any existing httpd ccache
  [14/19]: configuring SELinux for httpd
  [15/19]: create KDC proxy user
  [16/19]: create KDC proxy config
  [17/19]: enable KDC proxy
  [18/19]: restarting httpd
  [error] CalledProcessError: Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 10
ipa.ipapython.install.cli.install_tool(Server): ERROR    Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 10
FreeIPA server configuration failed.
No service definition found for [ipa-otpd.service].
Java virtual machine used: /usr/lib/jvm/jre/bin/java
classpath used: /usr/share/tomcat/bin/bootstrap.jar:/usr/share/tomcat/bin/tomcat-juli.jar:/usr/lib/java/commons-daemon.jar
main class used: org.apache.catalina.startup.Bootstrap
flags used:
options used: -Dcatalina.base=/usr/share/tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/cache/tomcat/temp -Djava.util.logging.config.file=/usr/share/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
arguments used: stop
```

```
2016-02-20T13:27:34Z DEBUG stderr=
2016-02-20T13:27:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-02-20T13:27:34Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2016-02-20T13:27:34Z DEBUG Starting external process
2016-02-20T13:27:34Z DEBUG args='/bin/systemctl' 'restart' 'httpd.service'
2016-02-20T13:28:25Z DEBUG Process finished, return code=10
2016-02-20T13:28:25Z DEBUG stdout=
2016-02-20T13:28:25Z DEBUG stderr=ipa         : INFO     KDC proxy enabled

2016-02-20T13:28:25Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 416, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 406, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/httpinstance.py", line 167, in __start
    self.restart()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 316, in restart
    self.service.restart(instance_name, capture_output=capture_output, wait=wait)
  File "/usr/lib/python2.7/site-packages/ipaplatform/base/services.py", line 314, in restart
    capture_output=capture_output)
  File "/usr/lib/python2.7/site-packages/ipapython/ipautil.py", line 373, in run
    raise CalledProcessError(p.returncode, arg_string, stdout)
CalledProcessError: Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 10

2016-02-20T13:28:25Z DEBUG   [error] CalledProcessError: Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 10
2016-02-20T13:28:25Z DEBUG   File "/usr/lib/python2.7/site-packages/ipapython/admintool.py", line 171, in execute
    return_value = self.run()
  File "/usr/lib/python2.7/site-packages/ipapython/install/cli.py", line 307, in run
    cfgr.run()
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 294, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 316, in execute
    for nothing in self._executor():
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 356, in __runner
    self._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 378, in _handle_exception
    util.raise_exc_info(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 346, in __runner
    step()
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 87, in run_generator_with_yield_from
    raise_exc_info(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 65, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 557, in _configure
    executor.next()
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 356, in __runner
    self._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 435, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 378, in _handle_exception
    util.raise_exc_info(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 432, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 378, in _handle_exception
    util.raise_exc_info(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 346, in __runner
    step()
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 87, in run_generator_with_yield_from
    raise_exc_info(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 65, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python2.7/site-packages/ipapython/install/common.py", line 63, in _install
    for nothing in self._installer(self.parent):
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 1285, in main
    install(self)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 257, in decorated
    func(installer)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 822, in install
    ca_is_configured=setup_ca)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/httpinstance.py", line 163, in create_instance
    self.start_creation(runtime=60)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 416, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 406, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/httpinstance.py", line 167, in __start
    self.restart()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 316, in restart
    self.service.restart(instance_name, capture_output=capture_output, wait=wait)
  File "/usr/lib/python2.7/site-packages/ipaplatform/base/services.py", line 314, in restart
    capture_output=capture_output)
  File "/usr/lib/python2.7/site-packages/ipapython/ipautil.py", line 373, in run
    raise CalledProcessError(p.returncode, arg_string, stdout)

2016-02-20T13:28:25Z DEBUG The ipa-server-install command failed, exception: CalledProcessError: Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 10
2016-02-20T13:28:25Z ERROR Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 10
```

If I create `$(pwd)/data/var/log/httpd` directory before running the container, the installation goes well.

**Comment by adelton** [comment]
Can you check the build log to see if some of the steps (probably installing the httpd package) yielded some errors (without failing) so that some things are not created properly?

**Comment by santosh0705** [comment]
I also got the same problem. I tried many times n got same issue.

**Comment by adelton** [comment]
> I also got the same problem. I tried many times n got same issue.

Can you check the build log to see if some of the steps (probably installing the httpd package) yielded some errors (without failing) so that some things are not created properly?

**Comment by santosh0705** [comment]
I pulled the image from Docker hub. Will try to build it and update.

**Comment by adelton** [comment]
> I pulled the image from Docker hub. Will try to build it and update.

Which image exactly? What is the exact `docker run` command that you use? What OS on the host?

**Comment by santosh0705** [comment]
I pulled the adelton/freeipa-server:latest image

created a file /srv/freeipa/ipa-server-install-options with following parameters:
`--ds-password=root@123
--admin-password=root@123`

command I'm using:
`docker run -ti --name freeipa-server -h freeipa.xyz.com -v /etc/localtime:/etc/localtime:ro -v /srv/freeipa:/data:Z adelton/freeipa-server`

**Comment by santosh0705** [comment]
I'm on Debian jessie

**Comment by adelton** [comment]
> I pulled the adelton/freeipa-server:latest image

Ah, checking the build logs it seems the Docker hub itself is hitting https://github.com/docker/docker/issues/6980. Sorry about the inconvenience. I've contacted Docker support.

Rebuilding the image locally without AUFS should give you working setup.

**Comment by santosh0705** [comment]
Local build successful with few errors but worked perfectly.
