### ISSUE TITLE
Upgrade fails to complete

### ISSUE THREAD

**Issue by frol** [adelton/docker-freeipa#88]
I haven't upgraded for a couple of months, so trying a new image today I got my FreeIPA broken.

Docker logs are almost useless:

```
FreeIPA server is already configured but with different version, volume update.
```

Here is the tail of `/var/log/ipaupgrade.log`:

```
2016-08-10T14:07:34Z DEBUG stderr=
2016-08-10T14:07:34Z DEBUG   duration: 1 seconds
2016-08-10T14:07:34Z DEBUG   [8/8]: restoring configuration
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG   duration: 0 seconds
2016-08-10T14:07:34Z DEBUG Done.
2016-08-10T14:07:34Z INFO Update complete
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysupgrade/sysupgrade.state'
2016-08-10T14:07:34Z DEBUG Saving StateFile to '/var/lib/ipa/sysupgrade/sysupgrade.state'
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysupgrade/sysupgrade.state'
2016-08-10T14:07:34Z DEBUG Saving StateFile to '/var/lib/ipa/sysupgrade/sysupgrade.state'
2016-08-10T14:07:34Z INFO Upgrading the configuration of the IPA services
2016-08-10T14:07:34Z DEBUG IPA version 4.3.1-1.fc24
2016-08-10T14:07:34Z DEBUG Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
2016-08-10T14:07:34Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2016-08-10T14:07:34Z DEBUG Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
2016-08-10T14:07:34Z DEBUG Starting external process
2016-08-10T14:07:34Z DEBUG args=/bin/systemctl is-active dirsrv@XXXFREEIPA-EXAMPLE-COM.service
2016-08-10T14:07:34Z DEBUG Process finished, return code=3
2016-08-10T14:07:34Z DEBUG stdout=inactive

2016-08-10T14:07:34Z DEBUG stderr=
2016-08-10T14:07:34Z DEBUG Starting external process
2016-08-10T14:07:34Z DEBUG args=/bin/systemctl start dirsrv@XXXFREEIPA-EXAMPLE-COM.service
2016-08-10T14:07:34Z DEBUG Process finished, return code=0
2016-08-10T14:07:34Z DEBUG stdout=
2016-08-10T14:07:34Z DEBUG stderr=
2016-08-10T14:07:34Z DEBUG Starting external process
2016-08-10T14:07:34Z DEBUG args=/bin/systemctl is-active dirsrv@XXXFREEIPA-EXAMPLE-COM.service
2016-08-10T14:07:34Z DEBUG Process finished, return code=0
2016-08-10T14:07:34Z DEBUG stdout=active

2016-08-10T14:07:34Z DEBUG stderr=
2016-08-10T14:07:34Z DEBUG wait_for_open_ports: localhost [389] timeout 300
```

Here is the output of `ps ax` once the `ipaupgrade.log` reaches that `wait_for_open_ports` lock:

```
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /usr/sbin/init --show-status=false
  151 ?        Ss     0:00 /usr/lib/systemd/systemd-journald
  157 ?        Ss     0:00 /bin/bash /usr/sbin/ipa-server-configure-first upgrade
  160 ?        Ss     0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
  166 ?        Ss     0:00 /usr/sbin/oddjobd -n -p /var/run/oddjobd.pid -t 300
  168 ?        Ss     0:00 /usr/sbin/certmonger -S -p /var/run/certmonger.pid -n
  170 ?        Ss     0:03 /usr/bin/python2 /usr/libexec/ipa/ipa-dnskeysyncd
  171 ?        Ss     0:00 /usr/sbin/sssd -D -f
  173 ?        S      0:00 /usr/libexec/sssd/sssd_be --domain xxxfreeipa.example.com --uid 0 --gid 0 --debug-to-files
  182 ?        S      0:00 /usr/libexec/sssd/sssd_nss --uid 0 --gid 0 --debug-to-files
  183 ?        S      0:00 /usr/libexec/sssd/sssd_sudo --uid 0 --gid 0 --debug-to-files
  184 ?        S      0:00 /usr/libexec/sssd/sssd_pam --uid 0 --gid 0 --debug-to-files
  185 ?        S      0:00 /usr/libexec/sssd/sssd_sudo --uid 0 --gid 0 --debug-to-files
  186 ?        S      0:00 /usr/libexec/sssd/sssd_pac --uid 0 --gid 0 --debug-to-files
  201 ?        S      0:01 /usr/bin/python2 -E /usr/libexec/certmonger/ipa-server-guard /usr/libexec/certmonger/ipa-submit
  202 ?        S      0:02 /usr/bin/python2 -E /usr/libexec/certmonger/ipa-server-guard /usr/libexec/certmonger/ipa-submit
  204 ?        S      0:02 /usr/bin/python2 -E /usr/libexec/certmonger/ipa-server-guard /usr/libexec/certmonger/ipa-submit
  221 ?        S      0:01 /usr/bin/python2 -E /usr/libexec/certmonger/ipa-server-guard /usr/libexec/certmonger/dogtag-ipa-renew-agent-submit
  545 ?        S      0:03 /usr/bin/python2 /usr/sbin/ipa-server-upgrade
  546 ?        Ss     0:00 bash
  575 ?        Ssl    0:01 /usr/sbin/ns-slapd -D /etc/dirsrv/slapd-XXXFREEIPA-EXAMPLE-COM -i /var/run/dirsrv/slapd-XXXFREEIPA-EXAMPLE-COM.pid
  619 ?        R+     0:00 ps ax
```

The output of `journalctl -a` revealed the following error message:

```
ipa-dnskeysyncd[162]: ipa         : CRITICAL Kerberos authentication failed: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639068): Cannot contact any KDC for realm 'XXXFREEIPA.EXAMPLE.COM'
ipa-dnskeysyncd.service: Main process exited, code=exited, status=1/FAILURE
ipa-dnskeysyncd.service: Unit entered failed state.
```

`ss -ltun` output is empty, so no processes listen on TCP/UDP sockets. Though, dirsrv is up and running using UNIX socket: 

```
NSACLPlugin - The ACL target cn=ad,cn=etc,dc=xxxfreeipa,dc=example,dc=com does not exist
NSACLPlugin - The ACL target cn=casigningcert cert-pki-ca,cn=ca_renewal,cn=ipa,cn=etc,dc=xxxfreeipa,dc=example,dc=com
NSACLPlugin - The ACL target cn=casigningcert cert-pki does not exist ca,cn=ca_renewal,cn=ipa,cn=etc,dc=xxxfreeipa,dc=example,dc=com does not exist
NSACLPlugin - The ACL target cn=automember rebuild membership,cn=tasks,cn=config does not exist
Skipping CoS Definition cn=Password Policy,cn=accounts,dc=xxxfreeipa,dc=example,dc=com--no CoS Templates found, which should be added before the CoS Definition.
schema-compat-plugin - schema-compat-plugin tree scan will start in about 5 seconds!
slapd started.  Listening on /var/run/slapd-xxxfreeipa-example-COM.socket for LDAPI requests
Started 389 Directory Server xxxfreeipa-example-COM..
schema-compat-plugin - warning: no entries set up under cn=computers, cn=compat,dc=xxxfreeipa,dc=example,dc=com
schema-compat-plugin - Finished plugin initialization.
```

Could you please help me to understand what is going on?

P.S. I have had this FreeIPA installation broken and fixed in #61. I haven't tried any forcing manual actions this time, but some side-effects might have just arisen this time...

**Comment by frol** [comment]
Ahm... Docker Hub has an outdated image from 7 weeks ago (https://hub.docker.com/r/adelton/freeipa-server/builds/). May it be the cause of my struggling? Are you going to fix the automatic builds?

**Comment by frol** [comment]
Building the image myself even with #89 fix didn't help. DirSrv is started fine listening only UNIX socket, but nobody listens on any TCP/UDP ports, and the upgrade script hangs waiting for 389 port to be ready.

**Comment by frol** [comment]
There is also the following error in the journal:

```
ntpd[180]: cap_set_proc() failed to drop root privileges: Operation not permitted
```

It is obvious that NTPD won't work inside Docker containers, so I assume that it should be safe to ignore this error, yet I went out of ideas and trying to document everything I see.

**Comment by frol** [comment]
I have modified `/etc/dirsrv/slapd-*/dse.ldif` changing `slapd-port: 0` to `slapd-port: 389` and the upgrade process went further crashing with a new error:

```
cat: /run/ipa/exit_code: No such file or directory
```

**Comment by frol** [comment]
Is this something that is fine?

```
sssd[197]: /usr/sbin/sssd: error while loading shared libraries: libnl-route-3.so.200: cannot open shared object file: Permission denied
```

**Comment by adelton** [comment]
You can use ```--no-ntp``` in the ```ipa-server-install``` options file to disable ntpd.

Alternatively, you can run ```docker run``` with ```--cap-add=SYS_TIME``` to allow the ntpd to operate.

**Comment by frol** [comment]
Currently, I manually patch `dse.ldif` with `s/slapd-port: 0/slapd-port:389/` and which gets me further, but I still struggle with the following error:

```
2016-08-11T15:04:09Z INFO [Migrating certificate profiles to LDAP]
2016-08-11T15:04:09Z DEBUG Created connection context.ldap2_139940073911120
2016-08-11T15:04:09Z DEBUG flushing ldapi://%2fvar%2frun%2fslapd-EXAMPLE-COM.socket from SchemaCache
2016-08-11T15:04:09Z DEBUG retrieving schema for SchemaCache url=ldapi://%2fvar%2frun%2fslapd-EXAMPLE-COM.socket conn=<ldap.ldapobject.SimpleLDAPObject instance at 0x7f465538f098>
2016-08-11T15:04:09Z DEBUG Destroyed connection context.ldap2_139940073911120
2016-08-11T15:04:09Z DEBUG request GET https://xxxfreeipa.example.com:8443/ca/rest/account/login
2016-08-11T15:04:09Z DEBUG request body ''
2016-08-11T15:04:09Z DEBUG NSSConnection init xxxfreeipa.example.com
2016-08-11T15:04:09Z DEBUG Connecting: 172.17.0.4
2016-08-11T15:04:09Z DEBUG Could not connect socket to 172.17.0.4, error: (PR_CONNECT_RESET_ERROR) TCP connection reset by peer.
2016-08-11T15:04:09Z DEBUG Try to continue with next family...
2016-08-11T15:04:09Z ERROR IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
2016-08-11T15:04:09Z DEBUG   File "/usr/lib/python2.7/site-packages/ipapython/admintool.py", line 171, in execute
    return_value = self.run()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/ipa_server_upgrade.py", line 48, in run
    server.upgrade()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/upgrade.py", line 1719, in upgrade
    upgrade_configuration()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/upgrade.py", line 1652, in upgrade_configuration
    ca_enable_ldap_profile_subsystem(ca)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/upgrade.py", line 339, in ca_enable_ldap_profile_subsystem
    cainstance.migrate_profiles_to_ldap()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/cainstance.py", line 1720, in migrate_profiles_to_ldap
    _create_dogtag_profile(profile_id, profile_data)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/cainstance.py", line 1726, in _create_dogtag_profile
    with api.Backend.ra_certprofile as profile_api:    File "/usr/lib/python2.7/site-packages/ipaserver/plugins/dogtag.py", line 2040, in __enter__
    method='GET'
  File "/usr/lib/python2.7/site-packages/ipapython/dogtag.py", line 161, in https_request      method=method, headers=headers)
  File "/usr/lib/python2.7/site-packages/ipapython/dogtag.py", line 226, in _httplib_request
    raise NetworkError(uri=uri, error=str(e))

2016-08-11T15:04:09Z DEBUG The ipa-server-upgrade command failed, exception: NetworkError: cannot connect to 'https://xxxfreeipa.example.com:8443/ca/rest/account/login': Could not connect to xxxfreeipa.example.com using any address: (PR_ADDRESS_NOT_SUPPORTED_ERROR) Network address type not supported.
2016-08-11T15:04:09Z ERROR Unexpected error - see /var/log/ipaupgrade.log for details:
NetworkError: cannot connect to 'https://xxxfreeipa.example.com:8443/ca/rest/account/login': Could not connect to xxxfreeipa.example.com using any address: (PR_ADDRESS_NOT_SUPPORTED_ERROR) Network address type not supported.
```

**Comment by frol** [comment]
Ah, it looks like FreeIPA 4.3.1 bug (https://fedorahosted.org/freeipa/ticket/5868), which was resolved only in the latest FreeIPA 4.3.2, which is still in `updates-testing` repo... Rebuilding the image again now with enabled `updates-testing` repo.

**Comment by frol** [comment]
I got through that one after the upgrade to 4.3.2, but there is another one:

```
2016-08-11T16:02:35Z DEBUG Waiting for CA to start...
2016-08-11T16:02:36Z DEBUG Starting external process
2016-08-11T16:02:36Z DEBUG args=/usr/bin/curl -o - --connect-timeout 30 -k https://freeipa.sparky.salford-systems.com:8443/ca/admin/ca/getStatus
2016-08-11T16:02:36Z DEBUG Process finished, return code=0
2016-08-11T16:02:36Z DEBUG stdout=<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 500 - Subsystem unavailable</h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u>Subsystem unavailable</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b></p><pre>javax.ws.rs.ServiceUnavailableException: Subsystem unavailable
        com.netscape.cms.tomcat.ProxyRealm.findSecurityConstraints(ProxyRealm.java:138)
        org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        java.lang.Thread.run(Thread.java:745)
</pre><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/8.0.32 logs.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32</h3></body></html>
2016-08-11T16:02:36Z DEBUG stderr=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2265  100  2265    0     0  18560      0 --:--:-- --:--:-- --:--:-- 18565

2016-08-11T16:02:36Z DEBUG The CA status is: check interrupted due to error: mismatched tag: line 14, column 165
```

**Comment by frol** [comment]
The previous error seems to be a result of the following:

```
server[854]: Internal Database Error encountered: Could not connect to LDAP server host xxxfreeipa.example.com port 636 Error netscape.ldap.LDAPException: IO Error creating JSS SSL Socket (-1)
[sssd[ldap_child[966]]][966]: Failed to initialize credentials using keytab [MEMORY:/etc/krb5.keytab]: Cannot contact any KDC for realm 'EXAMPLE.COM'. Unable to create GSSAPI-encrypted LDAP connection.
[sssd[ldap_child[966]]][966]: Cannot contact any KDC for realm 'EXAMPLE.COM'
[sssd[ldap_child[967]]][967]: Failed to initialize credentials using keytab [MEMORY:/etc/krb5.keytab]: Cannot contact any KDC for realm 'EXAMPLE.COM'. Unable to create GSSAPI-encrypted LDAP connection.
[sssd[ldap_child[967]]][967]: Cannot contact any KDC for realm 'EXAMPLE.COM'
```

It tries to connect to 636 which is not open.

```
# ss -ltn
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
LISTEN     0      1         ::ffff:127.0.0.1:8005                    :::*
LISTEN     0      128         :::389                     :::*
LISTEN     0      100       ::ffff:127.0.0.1:8009                    :::*
LISTEN     0      100         :::8080                    :::*
LISTEN     0      100         :::8443                    :::*
```

**Comment by frol** [comment]
It seems that all my issues arise from Fedora 24 and/or FreeIPA 4.3.x: https://www.redhat.com/archives/freeipa-users/2016-May/msg00507.html (the mailing continues in June: https://www.redhat.com/archives/freeipa-users/2016-June/msg00425.html).

I'm trying to go back to Fedora 23 at the moment, which has FreeIPA 4.2.

@adelton Do you use Fedora 24 installations?

**Comment by adelton** [comment]
Yes.

**Comment by frol** [comment]
I am trying to build the docker image on Arch Linux now to avoid #60. Hopefully, that will do the trick.

**Comment by frol** [comment]
I have built my image on Ubuntu 14.04 with `devicemapper` driver, and using this image I was able to boot FreeIPA services but `pki-tomcat`, which fails with the following error in the journal:

```
server[4924]: WARNING: Exception processing realm com.netscape.cms.tomcat.ProxyRealm@7e386e0e background process
server[4924]: javax.ws.rs.ServiceUnavailableException: Subsystem unavailable
server[4924]:         at com.netscape.cms.tomcat.ProxyRealm.backgroundProcess(ProxyRealm.java:130)
server[4924]:         at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1127)
server[4924]:         at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5642)
server[4924]:         at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1377)
server[4924]:         at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1381)
server[4924]:         at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1381)
server[4924]:         at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1349)
server[4924]:         at java.lang.Thread.run(Thread.java:745)
```

and 

```
# curl http://127.0.0.1:8080/ca/admin/ca/getStatus
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 500 - Subsystem unavailable</h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u>Subsystem unavailable</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b></p><pre>javax.ws.rs.ServiceUnavailableException: Subsystem unavailable
        com.netscape.cms.tomcat.ProxyRealm.findSecurityConstraints(ProxyRealm.java:138)
        org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        java.lang.Thread.run(Thread.java:745)
</pre><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/8.0.32 logs.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32</h3></body></html>
```

@adelton Could you please suggest what I can try to do about it?

**Comment by frol** [comment]
The above message is still reported to `pki-tomcatd@pki-tomcat.service`, yet FreeIPA web-UI and all connected services are working... I'm not going to touch this thing ever again...

**Comment by adelton** [comment]
No idea. I suggest taking this to freeipa-users mailing list.

**Comment by adelton** [comment]
I have reenabled automated builds on the Docker hub.

I have verified that upgrades work, even for images on the Docker hub -- both CentOS 7 and Fedora 23, 24.

Your best bet might be to create replica out of the existing master.

Please let me know if anything else is needed in this issue or if we can close it as I suspect that the broken `httpd` package installation was the source of all the troubles.

**Comment by adelton** [comment]
Closing now.
